build: regenerate package-lock.json due to NPM optional dependencies bug
Error: Cannot find module @rollup/rollup-linux-x64-gnu. https://github.com/npm/cli/issues/4828